! { dg-do run }
! PR 30389 - we now treat ACHAR equivalent to CHAR (except for
!            out of range-values) and IACHAR equivalent to ICHAR.
program main
  integer :: i
  character(len=1) :: c
  if (iachar(achar(1)) /= 1) stop 1
  if (iachar ("")/= 1) stop 1
  if (achar (1) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 1
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(2)) /= 2) stop 1
  if (iachar ("")/= 2) stop 1
  if (achar (2) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 2
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(3)) /= 3) stop 1
  if (iachar ("")/= 3) stop 1
  if (achar (3) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 3
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(4)) /= 4) stop 1
  if (iachar ("")/= 4) stop 1
  if (achar (4) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 4
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(5)) /= 5) stop 1
  if (iachar ("")/= 5) stop 1
  if (achar (5) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 5
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(6)) /= 6) stop 1
  if (iachar ("")/= 6) stop 1
  if (achar (6) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 6
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(7)) /= 7) stop 1
  if (iachar ("")/= 7) stop 1
  if (achar (7) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 7
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(8)) /= 8) stop 1
  if (iachar ("")/= 8) stop 1
  if (achar (8) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 8
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(9)) /= 9) stop 1
  if (iachar ("	")/= 9) stop 1
  if (achar (9) /= "	") stop 1
  if ("	" /= achar ( ichar ( "	"))) stop 1
  i = 9
  c = "	"
  if (achar(i) /= "	") stop 1
  if (iachar(c) /= iachar("	")) stop 1
  if (iachar(achar(10)) /= 10) stop 1
  if (iachar(achar(11)) /= 11) stop 1
  if (iachar ("")/= 11) stop 1
  if (achar (11) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 11
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(12)) /= 12) stop 1
  if (iachar ("")/= 12) stop 1
  if (achar (12) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 12
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(13)) /= 13) stop 1
  if (iachar(achar(14)) /= 14) stop 1
  if (iachar ("")/= 14) stop 1
  if (achar (14) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 14
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(15)) /= 15) stop 1
  if (iachar ("")/= 15) stop 1
  if (achar (15) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 15
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(16)) /= 16) stop 1
  if (iachar ("")/= 16) stop 1
  if (achar (16) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 16
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(17)) /= 17) stop 1
  if (iachar ("")/= 17) stop 1
  if (achar (17) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 17
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(18)) /= 18) stop 1
  if (iachar ("")/= 18) stop 1
  if (achar (18) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 18
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(19)) /= 19) stop 1
  if (iachar ("")/= 19) stop 1
  if (achar (19) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 19
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(20)) /= 20) stop 1
  if (iachar ("")/= 20) stop 1
  if (achar (20) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 20
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(21)) /= 21) stop 1
  if (iachar ("")/= 21) stop 1
  if (achar (21) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 21
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(22)) /= 22) stop 1
  if (iachar ("")/= 22) stop 1
  if (achar (22) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 22
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(23)) /= 23) stop 1
  if (iachar ("")/= 23) stop 1
  if (achar (23) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 23
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(24)) /= 24) stop 1
  if (iachar ("")/= 24) stop 1
  if (achar (24) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 24
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(25)) /= 25) stop 1
  if (iachar ("")/= 25) stop 1
  if (achar (25) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 25
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(26)) /= 26) stop 1
  if (iachar(achar(27)) /= 27) stop 1
  if (iachar ("")/= 27) stop 1
  if (achar (27) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 27
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(28)) /= 28) stop 1
  if (iachar ("")/= 28) stop 1
  if (achar (28) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 28
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(29)) /= 29) stop 1
  if (iachar ("")/= 29) stop 1
  if (achar (29) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 29
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(30)) /= 30) stop 1
  if (iachar ("")/= 30) stop 1
  if (achar (30) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 30
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(31)) /= 31) stop 1
  if (iachar ("")/= 31) stop 1
  if (achar (31) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 31
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(32)) /= 32) stop 1
  if (iachar (" ")/= 32) stop 1
  if (achar (32) /= " ") stop 1
  if (" " /= achar ( ichar ( " "))) stop 1
  i = 32
  c = " "
  if (achar(i) /= " ") stop 1
  if (iachar(c) /= iachar(" ")) stop 1
  if (iachar(achar(33)) /= 33) stop 1
  if (iachar ("!")/= 33) stop 1
  if (achar (33) /= "!") stop 1
  if ("!" /= achar ( ichar ( "!"))) stop 1
  i = 33
  c = "!"
  if (achar(i) /= "!") stop 1
  if (iachar(c) /= iachar("!")) stop 1
  if (iachar(achar(34)) /= 34) stop 1
  if (iachar ('"')/= 34) stop 1
  if (achar (34) /= '"') stop 1
  if ('"' /= achar ( ichar ( '"'))) stop 1
  i = 34
  c = '"'
  if (achar(i) /= '"') stop 1
  if (iachar(c) /= iachar('"')) stop 1
  if (iachar(achar(35)) /= 35) stop 1
  if (iachar ("#")/= 35) stop 1
  if (achar (35) /= "#") stop 1
  if ("#" /= achar ( ichar ( "#"))) stop 1
  i = 35
  c = "#"
  if (achar(i) /= "#") stop 1
  if (iachar(c) /= iachar("#")) stop 1
  if (iachar(achar(36)) /= 36) stop 1
  if (iachar ("$")/= 36) stop 1
  if (achar (36) /= "$") stop 1
  if ("$" /= achar ( ichar ( "$"))) stop 1
  i = 36
  c = "$"
  if (achar(i) /= "$") stop 1
  if (iachar(c) /= iachar("$")) stop 1
  if (iachar(achar(37)) /= 37) stop 1
  if (iachar ("%")/= 37) stop 1
  if (achar (37) /= "%") stop 1
  if ("%" /= achar ( ichar ( "%"))) stop 1
  i = 37
  c = "%"
  if (achar(i) /= "%") stop 1
  if (iachar(c) /= iachar("%")) stop 1
  if (iachar(achar(38)) /= 38) stop 1
  if (iachar ("&")/= 38) stop 1
  if (achar (38) /= "&") stop 1
  if ("&" /= achar ( ichar ( "&"))) stop 1
  i = 38
  c = "&"
  if (achar(i) /= "&") stop 1
  if (iachar(c) /= iachar("&")) stop 1
  if (iachar(achar(39)) /= 39) stop 1
  if (iachar ("'")/= 39) stop 1
  if (achar (39) /= "'") stop 1
  if ("'" /= achar ( ichar ( "'"))) stop 1
  i = 39
  c = "'"
  if (achar(i) /= "'") stop 1
  if (iachar(c) /= iachar("'")) stop 1
  if (iachar(achar(40)) /= 40) stop 1
  if (iachar ("(")/= 40) stop 1
  if (achar (40) /= "(") stop 1
  if ("(" /= achar ( ichar ( "("))) stop 1
  i = 40
  c = "("
  if (achar(i) /= "(") stop 1
  if (iachar(c) /= iachar("(")) stop 1
  if (iachar(achar(41)) /= 41) stop 1
  if (iachar (")")/= 41) stop 1
  if (achar (41) /= ")") stop 1
  if (")" /= achar ( ichar ( ")"))) stop 1
  i = 41
  c = ")"
  if (achar(i) /= ")") stop 1
  if (iachar(c) /= iachar(")")) stop 1
  if (iachar(achar(42)) /= 42) stop 1
  if (iachar ("*")/= 42) stop 1
  if (achar (42) /= "*") stop 1
  if ("*" /= achar ( ichar ( "*"))) stop 1
  i = 42
  c = "*"
  if (achar(i) /= "*") stop 1
  if (iachar(c) /= iachar("*")) stop 1
  if (iachar(achar(43)) /= 43) stop 1
  if (iachar ("+")/= 43) stop 1
  if (achar (43) /= "+") stop 1
  if ("+" /= achar ( ichar ( "+"))) stop 1
  i = 43
  c = "+"
  if (achar(i) /= "+") stop 1
  if (iachar(c) /= iachar("+")) stop 1
  if (iachar(achar(44)) /= 44) stop 1
  if (iachar (",")/= 44) stop 1
  if (achar (44) /= ",") stop 1
  if ("," /= achar ( ichar ( ","))) stop 1
  i = 44
  c = ","
  if (achar(i) /= ",") stop 1
  if (iachar(c) /= iachar(",")) stop 1
  if (iachar(achar(45)) /= 45) stop 1
  if (iachar ("-")/= 45) stop 1
  if (achar (45) /= "-") stop 1
  if ("-" /= achar ( ichar ( "-"))) stop 1
  i = 45
  c = "-"
  if (achar(i) /= "-") stop 1
  if (iachar(c) /= iachar("-")) stop 1
  if (iachar(achar(46)) /= 46) stop 1
  if (iachar (".")/= 46) stop 1
  if (achar (46) /= ".") stop 1
  if ("." /= achar ( ichar ( "."))) stop 1
  i = 46
  c = "."
  if (achar(i) /= ".") stop 1
  if (iachar(c) /= iachar(".")) stop 1
  if (iachar(achar(47)) /= 47) stop 1
  if (iachar ("/")/= 47) stop 1
  if (achar (47) /= "/") stop 1
  if ("/" /= achar ( ichar ( "/"))) stop 1
  i = 47
  c = "/"
  if (achar(i) /= "/") stop 1
  if (iachar(c) /= iachar("/")) stop 1
  if (iachar(achar(48)) /= 48) stop 1
  if (iachar ("0")/= 48) stop 1
  if (achar (48) /= "0") stop 1
  if ("0" /= achar ( ichar ( "0"))) stop 1
  i = 48
  c = "0"
  if (achar(i) /= "0") stop 1
  if (iachar(c) /= iachar("0")) stop 1
  if (iachar(achar(49)) /= 49) stop 1
  if (iachar ("1")/= 49) stop 1
  if (achar (49) /= "1") stop 1
  if ("1" /= achar ( ichar ( "1"))) stop 1
  i = 49
  c = "1"
  if (achar(i) /= "1") stop 1
  if (iachar(c) /= iachar("1")) stop 1
  if (iachar(achar(50)) /= 50) stop 1
  if (iachar ("2")/= 50) stop 1
  if (achar (50) /= "2") stop 1
  if ("2" /= achar ( ichar ( "2"))) stop 1
  i = 50
  c = "2"
  if (achar(i) /= "2") stop 1
  if (iachar(c) /= iachar("2")) stop 1
  if (iachar(achar(51)) /= 51) stop 1
  if (iachar ("3")/= 51) stop 1
  if (achar (51) /= "3") stop 1
  if ("3" /= achar ( ichar ( "3"))) stop 1
  i = 51
  c = "3"
  if (achar(i) /= "3") stop 1
  if (iachar(c) /= iachar("3")) stop 1
  if (iachar(achar(52)) /= 52) stop 1
  if (iachar ("4")/= 52) stop 1
  if (achar (52) /= "4") stop 1
  if ("4" /= achar ( ichar ( "4"))) stop 1
  i = 52
  c = "4"
  if (achar(i) /= "4") stop 1
  if (iachar(c) /= iachar("4")) stop 1
  if (iachar(achar(53)) /= 53) stop 1
  if (iachar ("5")/= 53) stop 1
  if (achar (53) /= "5") stop 1
  if ("5" /= achar ( ichar ( "5"))) stop 1
  i = 53
  c = "5"
  if (achar(i) /= "5") stop 1
  if (iachar(c) /= iachar("5")) stop 1
  if (iachar(achar(54)) /= 54) stop 1
  if (iachar ("6")/= 54) stop 1
  if (achar (54) /= "6") stop 1
  if ("6" /= achar ( ichar ( "6"))) stop 1
  i = 54
  c = "6"
  if (achar(i) /= "6") stop 1
  if (iachar(c) /= iachar("6")) stop 1
  if (iachar(achar(55)) /= 55) stop 1
  if (iachar ("7")/= 55) stop 1
  if (achar (55) /= "7") stop 1
  if ("7" /= achar ( ichar ( "7"))) stop 1
  i = 55
  c = "7"
  if (achar(i) /= "7") stop 1
  if (iachar(c) /= iachar("7")) stop 1
  if (iachar(achar(56)) /= 56) stop 1
  if (iachar ("8")/= 56) stop 1
  if (achar (56) /= "8") stop 1
  if ("8" /= achar ( ichar ( "8"))) stop 1
  i = 56
  c = "8"
  if (achar(i) /= "8") stop 1
  if (iachar(c) /= iachar("8")) stop 1
  if (iachar(achar(57)) /= 57) stop 1
  if (iachar ("9")/= 57) stop 1
  if (achar (57) /= "9") stop 1
  if ("9" /= achar ( ichar ( "9"))) stop 1
  i = 57
  c = "9"
  if (achar(i) /= "9") stop 1
  if (iachar(c) /= iachar("9")) stop 1
  if (iachar(achar(58)) /= 58) stop 1
  if (iachar (":")/= 58) stop 1
  if (achar (58) /= ":") stop 1
  if (":" /= achar ( ichar ( ":"))) stop 1
  i = 58
  c = ":"
  if (achar(i) /= ":") stop 1
  if (iachar(c) /= iachar(":")) stop 1
  if (iachar(achar(59)) /= 59) stop 1
  if (iachar (";")/= 59) stop 1
  if (achar (59) /= ";") stop 1
  if (";" /= achar ( ichar ( ";"))) stop 1
  i = 59
  c = ";"
  if (achar(i) /= ";") stop 1
  if (iachar(c) /= iachar(";")) stop 1
  if (iachar(achar(60)) /= 60) stop 1
  if (iachar ("<")/= 60) stop 1
  if (achar (60) /= "<") stop 1
  if ("<" /= achar ( ichar ( "<"))) stop 1
  i = 60
  c = "<"
  if (achar(i) /= "<") stop 1
  if (iachar(c) /= iachar("<")) stop 1
  if (iachar(achar(61)) /= 61) stop 1
  if (iachar ("=")/= 61) stop 1
  if (achar (61) /= "=") stop 1
  if ("=" /= achar ( ichar ( "="))) stop 1
  i = 61
  c = "="
  if (achar(i) /= "=") stop 1
  if (iachar(c) /= iachar("=")) stop 1
  if (iachar(achar(62)) /= 62) stop 1
  if (iachar (">")/= 62) stop 1
  if (achar (62) /= ">") stop 1
  if (">" /= achar ( ichar ( ">"))) stop 1
  i = 62
  c = ">"
  if (achar(i) /= ">") stop 1
  if (iachar(c) /= iachar(">")) stop 1
  if (iachar(achar(63)) /= 63) stop 1
  if (iachar ("?")/= 63) stop 1
  if (achar (63) /= "?") stop 1
  if ("?" /= achar ( ichar ( "?"))) stop 1
  i = 63
  c = "?"
  if (achar(i) /= "?") stop 1
  if (iachar(c) /= iachar("?")) stop 1
  if (iachar(achar(64)) /= 64) stop 1
  if (iachar ("@")/= 64) stop 1
  if (achar (64) /= "@") stop 1
  if ("@" /= achar ( ichar ( "@"))) stop 1
  i = 64
  c = "@"
  if (achar(i) /= "@") stop 1
  if (iachar(c) /= iachar("@")) stop 1
  if (iachar(achar(65)) /= 65) stop 1
  if (iachar ("A")/= 65) stop 1
  if (achar (65) /= "A") stop 1
  if ("A" /= achar ( ichar ( "A"))) stop 1
  i = 65
  c = "A"
  if (achar(i) /= "A") stop 1
  if (iachar(c) /= iachar("A")) stop 1
  if (iachar(achar(66)) /= 66) stop 1
  if (iachar ("B")/= 66) stop 1
  if (achar (66) /= "B") stop 1
  if ("B" /= achar ( ichar ( "B"))) stop 1
  i = 66
  c = "B"
  if (achar(i) /= "B") stop 1
  if (iachar(c) /= iachar("B")) stop 1
  if (iachar(achar(67)) /= 67) stop 1
  if (iachar ("C")/= 67) stop 1
  if (achar (67) /= "C") stop 1
  if ("C" /= achar ( ichar ( "C"))) stop 1
  i = 67
  c = "C"
  if (achar(i) /= "C") stop 1
  if (iachar(c) /= iachar("C")) stop 1
  if (iachar(achar(68)) /= 68) stop 1
  if (iachar ("D")/= 68) stop 1
  if (achar (68) /= "D") stop 1
  if ("D" /= achar ( ichar ( "D"))) stop 1
  i = 68
  c = "D"
  if (achar(i) /= "D") stop 1
  if (iachar(c) /= iachar("D")) stop 1
  if (iachar(achar(69)) /= 69) stop 1
  if (iachar ("E")/= 69) stop 1
  if (achar (69) /= "E") stop 1
  if ("E" /= achar ( ichar ( "E"))) stop 1
  i = 69
  c = "E"
  if (achar(i) /= "E") stop 1
  if (iachar(c) /= iachar("E")) stop 1
  if (iachar(achar(70)) /= 70) stop 1
  if (iachar ("F")/= 70) stop 1
  if (achar (70) /= "F") stop 1
  if ("F" /= achar ( ichar ( "F"))) stop 1
  i = 70
  c = "F"
  if (achar(i) /= "F") stop 1
  if (iachar(c) /= iachar("F")) stop 1
  if (iachar(achar(71)) /= 71) stop 1
  if (iachar ("G")/= 71) stop 1
  if (achar (71) /= "G") stop 1
  if ("G" /= achar ( ichar ( "G"))) stop 1
  i = 71
  c = "G"
  if (achar(i) /= "G") stop 1
  if (iachar(c) /= iachar("G")) stop 1
  if (iachar(achar(72)) /= 72) stop 1
  if (iachar ("H")/= 72) stop 1
  if (achar (72) /= "H") stop 1
  if ("H" /= achar ( ichar ( "H"))) stop 1
  i = 72
  c = "H"
  if (achar(i) /= "H") stop 1
  if (iachar(c) /= iachar("H")) stop 1
  if (iachar(achar(73)) /= 73) stop 1
  if (iachar ("I")/= 73) stop 1
  if (achar (73) /= "I") stop 1
  if ("I" /= achar ( ichar ( "I"))) stop 1
  i = 73
  c = "I"
  if (achar(i) /= "I") stop 1
  if (iachar(c) /= iachar("I")) stop 1
  if (iachar(achar(74)) /= 74) stop 1
  if (iachar ("J")/= 74) stop 1
  if (achar (74) /= "J") stop 1
  if ("J" /= achar ( ichar ( "J"))) stop 1
  i = 74
  c = "J"
  if (achar(i) /= "J") stop 1
  if (iachar(c) /= iachar("J")) stop 1
  if (iachar(achar(75)) /= 75) stop 1
  if (iachar ("K")/= 75) stop 1
  if (achar (75) /= "K") stop 1
  if ("K" /= achar ( ichar ( "K"))) stop 1
  i = 75
  c = "K"
  if (achar(i) /= "K") stop 1
  if (iachar(c) /= iachar("K")) stop 1
  if (iachar(achar(76)) /= 76) stop 1
  if (iachar ("L")/= 76) stop 1
  if (achar (76) /= "L") stop 1
  if ("L" /= achar ( ichar ( "L"))) stop 1
  i = 76
  c = "L"
  if (achar(i) /= "L") stop 1
  if (iachar(c) /= iachar("L")) stop 1
  if (iachar(achar(77)) /= 77) stop 1
  if (iachar ("M")/= 77) stop 1
  if (achar (77) /= "M") stop 1
  if ("M" /= achar ( ichar ( "M"))) stop 1
  i = 77
  c = "M"
  if (achar(i) /= "M") stop 1
  if (iachar(c) /= iachar("M")) stop 1
  if (iachar(achar(78)) /= 78) stop 1
  if (iachar ("N")/= 78) stop 1
  if (achar (78) /= "N") stop 1
  if ("N" /= achar ( ichar ( "N"))) stop 1
  i = 78
  c = "N"
  if (achar(i) /= "N") stop 1
  if (iachar(c) /= iachar("N")) stop 1
  if (iachar(achar(79)) /= 79) stop 1
  if (iachar ("O")/= 79) stop 1
  if (achar (79) /= "O") stop 1
  if ("O" /= achar ( ichar ( "O"))) stop 1
  i = 79
  c = "O"
  if (achar(i) /= "O") stop 1
  if (iachar(c) /= iachar("O")) stop 1
  if (iachar(achar(80)) /= 80) stop 1
  if (iachar ("P")/= 80) stop 1
  if (achar (80) /= "P") stop 1
  if ("P" /= achar ( ichar ( "P"))) stop 1
  i = 80
  c = "P"
  if (achar(i) /= "P") stop 1
  if (iachar(c) /= iachar("P")) stop 1
  if (iachar(achar(81)) /= 81) stop 1
  if (iachar ("Q")/= 81) stop 1
  if (achar (81) /= "Q") stop 1
  if ("Q" /= achar ( ichar ( "Q"))) stop 1
  i = 81
  c = "Q"
  if (achar(i) /= "Q") stop 1
  if (iachar(c) /= iachar("Q")) stop 1
  if (iachar(achar(82)) /= 82) stop 1
  if (iachar ("R")/= 82) stop 1
  if (achar (82) /= "R") stop 1
  if ("R" /= achar ( ichar ( "R"))) stop 1
  i = 82
  c = "R"
  if (achar(i) /= "R") stop 1
  if (iachar(c) /= iachar("R")) stop 1
  if (iachar(achar(83)) /= 83) stop 1
  if (iachar ("S")/= 83) stop 1
  if (achar (83) /= "S") stop 1
  if ("S" /= achar ( ichar ( "S"))) stop 1
  i = 83
  c = "S"
  if (achar(i) /= "S") stop 1
  if (iachar(c) /= iachar("S")) stop 1
  if (iachar(achar(84)) /= 84) stop 1
  if (iachar ("T")/= 84) stop 1
  if (achar (84) /= "T") stop 1
  if ("T" /= achar ( ichar ( "T"))) stop 1
  i = 84
  c = "T"
  if (achar(i) /= "T") stop 1
  if (iachar(c) /= iachar("T")) stop 1
  if (iachar(achar(85)) /= 85) stop 1
  if (iachar ("U")/= 85) stop 1
  if (achar (85) /= "U") stop 1
  if ("U" /= achar ( ichar ( "U"))) stop 1
  i = 85
  c = "U"
  if (achar(i) /= "U") stop 1
  if (iachar(c) /= iachar("U")) stop 1
  if (iachar(achar(86)) /= 86) stop 1
  if (iachar ("V")/= 86) stop 1
  if (achar (86) /= "V") stop 1
  if ("V" /= achar ( ichar ( "V"))) stop 1
  i = 86
  c = "V"
  if (achar(i) /= "V") stop 1
  if (iachar(c) /= iachar("V")) stop 1
  if (iachar(achar(87)) /= 87) stop 1
  if (iachar ("W")/= 87) stop 1
  if (achar (87) /= "W") stop 1
  if ("W" /= achar ( ichar ( "W"))) stop 1
  i = 87
  c = "W"
  if (achar(i) /= "W") stop 1
  if (iachar(c) /= iachar("W")) stop 1
  if (iachar(achar(88)) /= 88) stop 1
  if (iachar ("X")/= 88) stop 1
  if (achar (88) /= "X") stop 1
  if ("X" /= achar ( ichar ( "X"))) stop 1
  i = 88
  c = "X"
  if (achar(i) /= "X") stop 1
  if (iachar(c) /= iachar("X")) stop 1
  if (iachar(achar(89)) /= 89) stop 1
  if (iachar ("Y")/= 89) stop 1
  if (achar (89) /= "Y") stop 1
  if ("Y" /= achar ( ichar ( "Y"))) stop 1
  i = 89
  c = "Y"
  if (achar(i) /= "Y") stop 1
  if (iachar(c) /= iachar("Y")) stop 1
  if (iachar(achar(90)) /= 90) stop 1
  if (iachar ("Z")/= 90) stop 1
  if (achar (90) /= "Z") stop 1
  if ("Z" /= achar ( ichar ( "Z"))) stop 1
  i = 90
  c = "Z"
  if (achar(i) /= "Z") stop 1
  if (iachar(c) /= iachar("Z")) stop 1
  if (iachar(achar(91)) /= 91) stop 1
  if (iachar ("[")/= 91) stop 1
  if (achar (91) /= "[") stop 1
  if ("[" /= achar ( ichar ( "["))) stop 1
  i = 91
  c = "["
  if (achar(i) /= "[") stop 1
  if (iachar(c) /= iachar("[")) stop 1
  if (iachar(achar(92)) /= 92) stop 1
  if (iachar ("\")/= 92) stop 1
  if (achar (92) /= "\") stop 1
  if ("\" /= achar ( ichar ( "\"))) stop 1
  i = 92
  c = "\"
  if (achar(i) /= "\") stop 1
  if (iachar(c) /= iachar("\")) stop 1
  if (iachar(achar(93)) /= 93) stop 1
  if (iachar ("]")/= 93) stop 1
  if (achar (93) /= "]") stop 1
  if ("]" /= achar ( ichar ( "]"))) stop 1
  i = 93
  c = "]"
  if (achar(i) /= "]") stop 1
  if (iachar(c) /= iachar("]")) stop 1
  if (iachar(achar(94)) /= 94) stop 1
  if (iachar ("^")/= 94) stop 1
  if (achar (94) /= "^") stop 1
  if ("^" /= achar ( ichar ( "^"))) stop 1
  i = 94
  c = "^"
  if (achar(i) /= "^") stop 1
  if (iachar(c) /= iachar("^")) stop 1
  if (iachar(achar(95)) /= 95) stop 1
  if (iachar ("_")/= 95) stop 1
  if (achar (95) /= "_") stop 1
  if ("_" /= achar ( ichar ( "_"))) stop 1
  i = 95
  c = "_"
  if (achar(i) /= "_") stop 1
  if (iachar(c) /= iachar("_")) stop 1
  if (iachar(achar(96)) /= 96) stop 1
  if (iachar ("`")/= 96) stop 1
  if (achar (96) /= "`") stop 1
  if ("`" /= achar ( ichar ( "`"))) stop 1
  i = 96
  c = "`"
  if (achar(i) /= "`") stop 1
  if (iachar(c) /= iachar("`")) stop 1
  if (iachar(achar(97)) /= 97) stop 1
  if (iachar ("a")/= 97) stop 1
  if (achar (97) /= "a") stop 1
  if ("a" /= achar ( ichar ( "a"))) stop 1
  i = 97
  c = "a"
  if (achar(i) /= "a") stop 1
  if (iachar(c) /= iachar("a")) stop 1
  if (iachar(achar(98)) /= 98) stop 1
  if (iachar ("b")/= 98) stop 1
  if (achar (98) /= "b") stop 1
  if ("b" /= achar ( ichar ( "b"))) stop 1
  i = 98
  c = "b"
  if (achar(i) /= "b") stop 1
  if (iachar(c) /= iachar("b")) stop 1
  if (iachar(achar(99)) /= 99) stop 1
  if (iachar ("c")/= 99) stop 1
  if (achar (99) /= "c") stop 1
  if ("c" /= achar ( ichar ( "c"))) stop 1
  i = 99
  c = "c"
  if (achar(i) /= "c") stop 1
  if (iachar(c) /= iachar("c")) stop 1
  if (iachar(achar(100)) /= 100) stop 1
  if (iachar ("d")/= 100) stop 1
  if (achar (100) /= "d") stop 1
  if ("d" /= achar ( ichar ( "d"))) stop 1
  i = 100
  c = "d"
  if (achar(i) /= "d") stop 1
  if (iachar(c) /= iachar("d")) stop 1
  if (iachar(achar(101)) /= 101) stop 1
  if (iachar ("e")/= 101) stop 1
  if (achar (101) /= "e") stop 1
  if ("e" /= achar ( ichar ( "e"))) stop 1
  i = 101
  c = "e"
  if (achar(i) /= "e") stop 1
  if (iachar(c) /= iachar("e")) stop 1
  if (iachar(achar(102)) /= 102) stop 1
  if (iachar ("f")/= 102) stop 1
  if (achar (102) /= "f") stop 1
  if ("f" /= achar ( ichar ( "f"))) stop 1
  i = 102
  c = "f"
  if (achar(i) /= "f") stop 1
  if (iachar(c) /= iachar("f")) stop 1
  if (iachar(achar(103)) /= 103) stop 1
  if (iachar ("g")/= 103) stop 1
  if (achar (103) /= "g") stop 1
  if ("g" /= achar ( ichar ( "g"))) stop 1
  i = 103
  c = "g"
  if (achar(i) /= "g") stop 1
  if (iachar(c) /= iachar("g")) stop 1
  if (iachar(achar(104)) /= 104) stop 1
  if (iachar ("h")/= 104) stop 1
  if (achar (104) /= "h") stop 1
  if ("h" /= achar ( ichar ( "h"))) stop 1
  i = 104
  c = "h"
  if (achar(i) /= "h") stop 1
  if (iachar(c) /= iachar("h")) stop 1
  if (iachar(achar(105)) /= 105) stop 1
  if (iachar ("i")/= 105) stop 1
  if (achar (105) /= "i") stop 1
  if ("i" /= achar ( ichar ( "i"))) stop 1
  i = 105
  c = "i"
  if (achar(i) /= "i") stop 1
  if (iachar(c) /= iachar("i")) stop 1
  if (iachar(achar(106)) /= 106) stop 1
  if (iachar ("j")/= 106) stop 1
  if (achar (106) /= "j") stop 1
  if ("j" /= achar ( ichar ( "j"))) stop 1
  i = 106
  c = "j"
  if (achar(i) /= "j") stop 1
  if (iachar(c) /= iachar("j")) stop 1
  if (iachar(achar(107)) /= 107) stop 1
  if (iachar ("k")/= 107) stop 1
  if (achar (107) /= "k") stop 1
  if ("k" /= achar ( ichar ( "k"))) stop 1
  i = 107
  c = "k"
  if (achar(i) /= "k") stop 1
  if (iachar(c) /= iachar("k")) stop 1
  if (iachar(achar(108)) /= 108) stop 1
  if (iachar ("l")/= 108) stop 1
  if (achar (108) /= "l") stop 1
  if ("l" /= achar ( ichar ( "l"))) stop 1
  i = 108
  c = "l"
  if (achar(i) /= "l") stop 1
  if (iachar(c) /= iachar("l")) stop 1
  if (iachar(achar(109)) /= 109) stop 1
  if (iachar ("m")/= 109) stop 1
  if (achar (109) /= "m") stop 1
  if ("m" /= achar ( ichar ( "m"))) stop 1
  i = 109
  c = "m"
  if (achar(i) /= "m") stop 1
  if (iachar(c) /= iachar("m")) stop 1
  if (iachar(achar(110)) /= 110) stop 1
  if (iachar ("n")/= 110) stop 1
  if (achar (110) /= "n") stop 1
  if ("n" /= achar ( ichar ( "n"))) stop 1
  i = 110
  c = "n"
  if (achar(i) /= "n") stop 1
  if (iachar(c) /= iachar("n")) stop 1
  if (iachar(achar(111)) /= 111) stop 1
  if (iachar ("o")/= 111) stop 1
  if (achar (111) /= "o") stop 1
  if ("o" /= achar ( ichar ( "o"))) stop 1
  i = 111
  c = "o"
  if (achar(i) /= "o") stop 1
  if (iachar(c) /= iachar("o")) stop 1
  if (iachar(achar(112)) /= 112) stop 1
  if (iachar ("p")/= 112) stop 1
  if (achar (112) /= "p") stop 1
  if ("p" /= achar ( ichar ( "p"))) stop 1
  i = 112
  c = "p"
  if (achar(i) /= "p") stop 1
  if (iachar(c) /= iachar("p")) stop 1
  if (iachar(achar(113)) /= 113) stop 1
  if (iachar ("q")/= 113) stop 1
  if (achar (113) /= "q") stop 1
  if ("q" /= achar ( ichar ( "q"))) stop 1
  i = 113
  c = "q"
  if (achar(i) /= "q") stop 1
  if (iachar(c) /= iachar("q")) stop 1
  if (iachar(achar(114)) /= 114) stop 1
  if (iachar ("r")/= 114) stop 1
  if (achar (114) /= "r") stop 1
  if ("r" /= achar ( ichar ( "r"))) stop 1
  i = 114
  c = "r"
  if (achar(i) /= "r") stop 1
  if (iachar(c) /= iachar("r")) stop 1
  if (iachar(achar(115)) /= 115) stop 1
  if (iachar ("s")/= 115) stop 1
  if (achar (115) /= "s") stop 1
  if ("s" /= achar ( ichar ( "s"))) stop 1
  i = 115
  c = "s"
  if (achar(i) /= "s") stop 1
  if (iachar(c) /= iachar("s")) stop 1
  if (iachar(achar(116)) /= 116) stop 1
  if (iachar ("t")/= 116) stop 1
  if (achar (116) /= "t") stop 1
  if ("t" /= achar ( ichar ( "t"))) stop 1
  i = 116
  c = "t"
  if (achar(i) /= "t") stop 1
  if (iachar(c) /= iachar("t")) stop 1
  if (iachar(achar(117)) /= 117) stop 1
  if (iachar ("u")/= 117) stop 1
  if (achar (117) /= "u") stop 1
  if ("u" /= achar ( ichar ( "u"))) stop 1
  i = 117
  c = "u"
  if (achar(i) /= "u") stop 1
  if (iachar(c) /= iachar("u")) stop 1
  if (iachar(achar(118)) /= 118) stop 1
  if (iachar ("v")/= 118) stop 1
  if (achar (118) /= "v") stop 1
  if ("v" /= achar ( ichar ( "v"))) stop 1
  i = 118
  c = "v"
  if (achar(i) /= "v") stop 1
  if (iachar(c) /= iachar("v")) stop 1
  if (iachar(achar(119)) /= 119) stop 1
  if (iachar ("w")/= 119) stop 1
  if (achar (119) /= "w") stop 1
  if ("w" /= achar ( ichar ( "w"))) stop 1
  i = 119
  c = "w"
  if (achar(i) /= "w") stop 1
  if (iachar(c) /= iachar("w")) stop 1
  if (iachar(achar(120)) /= 120) stop 1
  if (iachar ("x")/= 120) stop 1
  if (achar (120) /= "x") stop 1
  if ("x" /= achar ( ichar ( "x"))) stop 1
  i = 120
  c = "x"
  if (achar(i) /= "x") stop 1
  if (iachar(c) /= iachar("x")) stop 1
  if (iachar(achar(121)) /= 121) stop 1
  if (iachar ("y")/= 121) stop 1
  if (achar (121) /= "y") stop 1
  if ("y" /= achar ( ichar ( "y"))) stop 1
  i = 121
  c = "y"
  if (achar(i) /= "y") stop 1
  if (iachar(c) /= iachar("y")) stop 1
  if (iachar(achar(122)) /= 122) stop 1
  if (iachar ("z")/= 122) stop 1
  if (achar (122) /= "z") stop 1
  if ("z" /= achar ( ichar ( "z"))) stop 1
  i = 122
  c = "z"
  if (achar(i) /= "z") stop 1
  if (iachar(c) /= iachar("z")) stop 1
  if (iachar(achar(123)) /= 123) stop 1
  if (iachar ("{")/= 123) stop 1
  if (achar (123) /= "{") stop 1
  if ("{" /= achar ( ichar ( "{"))) stop 1
  i = 123
  c = "{"
  if (achar(i) /= "{") stop 1
  if (iachar(c) /= iachar("{")) stop 1
  if (iachar(achar(124)) /= 124) stop 1
  if (iachar ("|")/= 124) stop 1
  if (achar (124) /= "|") stop 1
  if ("|" /= achar ( ichar ( "|"))) stop 1
  i = 124
  c = "|"
  if (achar(i) /= "|") stop 1
  if (iachar(c) /= iachar("|")) stop 1
  if (iachar(achar(125)) /= 125) stop 1
  if (iachar ("}")/= 125) stop 1
  if (achar (125) /= "}") stop 1
  if ("}" /= achar ( ichar ( "}"))) stop 1
  i = 125
  c = "}"
  if (achar(i) /= "}") stop 1
  if (iachar(c) /= iachar("}")) stop 1
  if (iachar(achar(126)) /= 126) stop 1
  if (iachar ("~")/= 126) stop 1
  if (achar (126) /= "~") stop 1
  if ("~" /= achar ( ichar ( "~"))) stop 1
  i = 126
  c = "~"
  if (achar(i) /= "~") stop 1
  if (iachar(c) /= iachar("~")) stop 1
  if (iachar(achar(127)) /= 127) stop 1
  if (iachar ("")/= 127) stop 1
  if (achar (127) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 127
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(128)) /= 128) stop 1
  if (iachar ("Ä")/= 128) stop 1
  if (achar (128) /= "Ä") stop 1
  if ("Ä" /= achar ( ichar ( "Ä"))) stop 1
  i = 128
  c = "Ä"
  if (achar(i) /= "Ä") stop 1
  if (iachar(c) /= iachar("Ä")) stop 1
  if (iachar(achar(129)) /= 129) stop 1
  if (iachar ("Å")/= 129) stop 1
  if (achar (129) /= "Å") stop 1
  if ("Å" /= achar ( ichar ( "Å"))) stop 1
  i = 129
  c = "Å"
  if (achar(i) /= "Å") stop 1
  if (iachar(c) /= iachar("Å")) stop 1
  if (iachar(achar(130)) /= 130) stop 1
  if (iachar ("Ç")/= 130) stop 1
  if (achar (130) /= "Ç") stop 1
  if ("Ç" /= achar ( ichar ( "Ç"))) stop 1
  i = 130
  c = "Ç"
  if (achar(i) /= "Ç") stop 1
  if (iachar(c) /= iachar("Ç")) stop 1
  if (iachar(achar(131)) /= 131) stop 1
  if (iachar ("É")/= 131) stop 1
  if (achar (131) /= "É") stop 1
  if ("É" /= achar ( ichar ( "É"))) stop 1
  i = 131
  c = "É"
  if (achar(i) /= "É") stop 1
  if (iachar(c) /= iachar("É")) stop 1
  if (iachar(achar(132)) /= 132) stop 1
  if (iachar ("Ñ")/= 132) stop 1
  if (achar (132) /= "Ñ") stop 1
  if ("Ñ" /= achar ( ichar ( "Ñ"))) stop 1
  i = 132
  c = "Ñ"
  if (achar(i) /= "Ñ") stop 1
  if (iachar(c) /= iachar("Ñ")) stop 1
  if (iachar(achar(133)) /= 133) stop 1
  if (iachar ("Ö")/= 133) stop 1
  if (achar (133) /= "Ö") stop 1
  if ("Ö" /= achar ( ichar ( "Ö"))) stop 1
  i = 133
  c = "Ö"
  if (achar(i) /= "Ö") stop 1
  if (iachar(c) /= iachar("Ö")) stop 1
  if (iachar(achar(134)) /= 134) stop 1
  if (iachar ("Ü")/= 134) stop 1
  if (achar (134) /= "Ü") stop 1
  if ("Ü" /= achar ( ichar ( "Ü"))) stop 1
  i = 134
  c = "Ü"
  if (achar(i) /= "Ü") stop 1
  if (iachar(c) /= iachar("Ü")) stop 1
  if (iachar(achar(135)) /= 135) stop 1
  if (iachar ("á")/= 135) stop 1
  if (achar (135) /= "á") stop 1
  if ("á" /= achar ( ichar ( "á"))) stop 1
  i = 135
  c = "á"
  if (achar(i) /= "á") stop 1
  if (iachar(c) /= iachar("á")) stop 1
  if (iachar(achar(136)) /= 136) stop 1
  if (iachar ("à")/= 136) stop 1
  if (achar (136) /= "à") stop 1
  if ("à" /= achar ( ichar ( "à"))) stop 1
  i = 136
  c = "à"
  if (achar(i) /= "à") stop 1
  if (iachar(c) /= iachar("à")) stop 1
  if (iachar(achar(137)) /= 137) stop 1
  if (iachar ("â")/= 137) stop 1
  if (achar (137) /= "â") stop 1
  if ("â" /= achar ( ichar ( "â"))) stop 1
  i = 137
  c = "â"
  if (achar(i) /= "â") stop 1
  if (iachar(c) /= iachar("â")) stop 1
  if (iachar(achar(138)) /= 138) stop 1
  if (iachar ("ä")/= 138) stop 1
  if (achar (138) /= "ä") stop 1
  if ("ä" /= achar ( ichar ( "ä"))) stop 1
  i = 138
  c = "ä"
  if (achar(i) /= "ä") stop 1
  if (iachar(c) /= iachar("ä")) stop 1
  if (iachar(achar(139)) /= 139) stop 1
  if (iachar ("ã")/= 139) stop 1
  if (achar (139) /= "ã") stop 1
  if ("ã" /= achar ( ichar ( "ã"))) stop 1
  i = 139
  c = "ã"
  if (achar(i) /= "ã") stop 1
  if (iachar(c) /= iachar("ã")) stop 1
  if (iachar(achar(140)) /= 140) stop 1
  if (iachar ("å")/= 140) stop 1
  if (achar (140) /= "å") stop 1
  if ("å" /= achar ( ichar ( "å"))) stop 1
  i = 140
  c = "å"
  if (achar(i) /= "å") stop 1
  if (iachar(c) /= iachar("å")) stop 1
  if (iachar(achar(141)) /= 141) stop 1
  if (iachar ("ç")/= 141) stop 1
  if (achar (141) /= "ç") stop 1
  if ("ç" /= achar ( ichar ( "ç"))) stop 1
  i = 141
  c = "ç"
  if (achar(i) /= "ç") stop 1
  if (iachar(c) /= iachar("ç")) stop 1
  if (iachar(achar(142)) /= 142) stop 1
  if (iachar ("é")/= 142) stop 1
  if (achar (142) /= "é") stop 1
  if ("é" /= achar ( ichar ( "é"))) stop 1
  i = 142
  c = "é"
  if (achar(i) /= "é") stop 1
  if (iachar(c) /= iachar("é")) stop 1
  if (iachar(achar(143)) /= 143) stop 1
  if (iachar ("è")/= 143) stop 1
  if (achar (143) /= "è") stop 1
  if ("è" /= achar ( ichar ( "è"))) stop 1
  i = 143
  c = "è"
  if (achar(i) /= "è") stop 1
  if (iachar(c) /= iachar("è")) stop 1
  if (iachar(achar(144)) /= 144) stop 1
  if (iachar ("ê")/= 144) stop 1
  if (achar (144) /= "ê") stop 1
  if ("ê" /= achar ( ichar ( "ê"))) stop 1
  i = 144
  c = "ê"
  if (achar(i) /= "ê") stop 1
  if (iachar(c) /= iachar("ê")) stop 1
  if (iachar(achar(145)) /= 145) stop 1
  if (iachar ("ë")/= 145) stop 1
  if (achar (145) /= "ë") stop 1
  if ("ë" /= achar ( ichar ( "ë"))) stop 1
  i = 145
  c = "ë"
  if (achar(i) /= "ë") stop 1
  if (iachar(c) /= iachar("ë")) stop 1
  if (iachar(achar(146)) /= 146) stop 1
  if (iachar ("í")/= 146) stop 1
  if (achar (146) /= "í") stop 1
  if ("í" /= achar ( ichar ( "í"))) stop 1
  i = 146
  c = "í"
  if (achar(i) /= "í") stop 1
  if (iachar(c) /= iachar("í")) stop 1
  if (iachar(achar(147)) /= 147) stop 1
  if (iachar ("ì")/= 147) stop 1
  if (achar (147) /= "ì") stop 1
  if ("ì" /= achar ( ichar ( "ì"))) stop 1
  i = 147
  c = "ì"
  if (achar(i) /= "ì") stop 1
  if (iachar(c) /= iachar("ì")) stop 1
  if (iachar(achar(148)) /= 148) stop 1
  if (iachar ("î")/= 148) stop 1
  if (achar (148) /= "î") stop 1
  if ("î" /= achar ( ichar ( "î"))) stop 1
  i = 148
  c = "î"
  if (achar(i) /= "î") stop 1
  if (iachar(c) /= iachar("î")) stop 1
  if (iachar(achar(149)) /= 149) stop 1
  if (iachar ("ï")/= 149) stop 1
  if (achar (149) /= "ï") stop 1
  if ("ï" /= achar ( ichar ( "ï"))) stop 1
  i = 149
  c = "ï"
  if (achar(i) /= "ï") stop 1
  if (iachar(c) /= iachar("ï")) stop 1
  if (iachar(achar(150)) /= 150) stop 1
  if (iachar ("ñ")/= 150) stop 1
  if (achar (150) /= "ñ") stop 1
  if ("ñ" /= achar ( ichar ( "ñ"))) stop 1
  i = 150
  c = "ñ"
  if (achar(i) /= "ñ") stop 1
  if (iachar(c) /= iachar("ñ")) stop 1
  if (iachar(achar(151)) /= 151) stop 1
  if (iachar ("ó")/= 151) stop 1
  if (achar (151) /= "ó") stop 1
  if ("ó" /= achar ( ichar ( "ó"))) stop 1
  i = 151
  c = "ó"
  if (achar(i) /= "ó") stop 1
  if (iachar(c) /= iachar("ó")) stop 1
  if (iachar(achar(152)) /= 152) stop 1
  if (iachar ("ò")/= 152) stop 1
  if (achar (152) /= "ò") stop 1
  if ("ò" /= achar ( ichar ( "ò"))) stop 1
  i = 152
  c = "ò"
  if (achar(i) /= "ò") stop 1
  if (iachar(c) /= iachar("ò")) stop 1
  if (iachar(achar(153)) /= 153) stop 1
  if (iachar ("ô")/= 153) stop 1
  if (achar (153) /= "ô") stop 1
  if ("ô" /= achar ( ichar ( "ô"))) stop 1
  i = 153
  c = "ô"
  if (achar(i) /= "ô") stop 1
  if (iachar(c) /= iachar("ô")) stop 1
  if (iachar(achar(154)) /= 154) stop 1
  if (iachar ("ö")/= 154) stop 1
  if (achar (154) /= "ö") stop 1
  if ("ö" /= achar ( ichar ( "ö"))) stop 1
  i = 154
  c = "ö"
  if (achar(i) /= "ö") stop 1
  if (iachar(c) /= iachar("ö")) stop 1
  if (iachar(achar(155)) /= 155) stop 1
  if (iachar ("õ")/= 155) stop 1
  if (achar (155) /= "õ") stop 1
  if ("õ" /= achar ( ichar ( "õ"))) stop 1
  i = 155
  c = "õ"
  if (achar(i) /= "õ") stop 1
  if (iachar(c) /= iachar("õ")) stop 1
  if (iachar(achar(156)) /= 156) stop 1
  if (iachar ("ú")/= 156) stop 1
  if (achar (156) /= "ú") stop 1
  if ("ú" /= achar ( ichar ( "ú"))) stop 1
  i = 156
  c = "ú"
  if (achar(i) /= "ú") stop 1
  if (iachar(c) /= iachar("ú")) stop 1
  if (iachar(achar(157)) /= 157) stop 1
  if (iachar ("ù")/= 157) stop 1
  if (achar (157) /= "ù") stop 1
  if ("ù" /= achar ( ichar ( "ù"))) stop 1
  i = 157
  c = "ù"
  if (achar(i) /= "ù") stop 1
  if (iachar(c) /= iachar("ù")) stop 1
  if (iachar(achar(158)) /= 158) stop 1
  if (iachar ("û")/= 158) stop 1
  if (achar (158) /= "û") stop 1
  if ("û" /= achar ( ichar ( "û"))) stop 1
  i = 158
  c = "û"
  if (achar(i) /= "û") stop 1
  if (iachar(c) /= iachar("û")) stop 1
  if (iachar(achar(159)) /= 159) stop 1
  if (iachar ("ü")/= 159) stop 1
  if (achar (159) /= "ü") stop 1
  if ("ü" /= achar ( ichar ( "ü"))) stop 1
  i = 159
  c = "ü"
  if (achar(i) /= "ü") stop 1
  if (iachar(c) /= iachar("ü")) stop 1
  if (iachar(achar(160)) /= 160) stop 1
  if (iachar ("†")/= 160) stop 1
  if (achar (160) /= "†") stop 1
  if ("†" /= achar ( ichar ( "†"))) stop 1
  i = 160
  c = "†"
  if (achar(i) /= "†") stop 1
  if (iachar(c) /= iachar("†")) stop 1
  if (iachar(achar(161)) /= 161) stop 1
  if (iachar ("°")/= 161) stop 1
  if (achar (161) /= "°") stop 1
  if ("°" /= achar ( ichar ( "°"))) stop 1
  i = 161
  c = "°"
  if (achar(i) /= "°") stop 1
  if (iachar(c) /= iachar("°")) stop 1
  if (iachar(achar(162)) /= 162) stop 1
  if (iachar ("¢")/= 162) stop 1
  if (achar (162) /= "¢") stop 1
  if ("¢" /= achar ( ichar ( "¢"))) stop 1
  i = 162
  c = "¢"
  if (achar(i) /= "¢") stop 1
  if (iachar(c) /= iachar("¢")) stop 1
  if (iachar(achar(163)) /= 163) stop 1
  if (iachar ("£")/= 163) stop 1
  if (achar (163) /= "£") stop 1
  if ("£" /= achar ( ichar ( "£"))) stop 1
  i = 163
  c = "£"
  if (achar(i) /= "£") stop 1
  if (iachar(c) /= iachar("£")) stop 1
  if (iachar(achar(164)) /= 164) stop 1
  if (iachar ("§")/= 164) stop 1
  if (achar (164) /= "§") stop 1
  if ("§" /= achar ( ichar ( "§"))) stop 1
  i = 164
  c = "§"
  if (achar(i) /= "§") stop 1
  if (iachar(c) /= iachar("§")) stop 1
  if (iachar(achar(165)) /= 165) stop 1
  if (iachar ("•")/= 165) stop 1
  if (achar (165) /= "•") stop 1
  if ("•" /= achar ( ichar ( "•"))) stop 1
  i = 165
  c = "•"
  if (achar(i) /= "•") stop 1
  if (iachar(c) /= iachar("•")) stop 1
  if (iachar(achar(166)) /= 166) stop 1
  if (iachar ("¶")/= 166) stop 1
  if (achar (166) /= "¶") stop 1
  if ("¶" /= achar ( ichar ( "¶"))) stop 1
  i = 166
  c = "¶"
  if (achar(i) /= "¶") stop 1
  if (iachar(c) /= iachar("¶")) stop 1
  if (iachar(achar(167)) /= 167) stop 1
  if (iachar ("ß")/= 167) stop 1
  if (achar (167) /= "ß") stop 1
  if ("ß" /= achar ( ichar ( "ß"))) stop 1
  i = 167
  c = "ß"
  if (achar(i) /= "ß") stop 1
  if (iachar(c) /= iachar("ß")) stop 1
  if (iachar(achar(168)) /= 168) stop 1
  if (iachar ("®")/= 168) stop 1
  if (achar (168) /= "®") stop 1
  if ("®" /= achar ( ichar ( "®"))) stop 1
  i = 168
  c = "®"
  if (achar(i) /= "®") stop 1
  if (iachar(c) /= iachar("®")) stop 1
  if (iachar(achar(169)) /= 169) stop 1
  if (iachar ("©")/= 169) stop 1
  if (achar (169) /= "©") stop 1
  if ("©" /= achar ( ichar ( "©"))) stop 1
  i = 169
  c = "©"
  if (achar(i) /= "©") stop 1
  if (iachar(c) /= iachar("©")) stop 1
  if (iachar(achar(170)) /= 170) stop 1
  if (iachar ("™")/= 170) stop 1
  if (achar (170) /= "™") stop 1
  if ("™" /= achar ( ichar ( "™"))) stop 1
  i = 170
  c = "™"
  if (achar(i) /= "™") stop 1
  if (iachar(c) /= iachar("™")) stop 1
  if (iachar(achar(171)) /= 171) stop 1
  if (iachar ("´")/= 171) stop 1
  if (achar (171) /= "´") stop 1
  if ("´" /= achar ( ichar ( "´"))) stop 1
  i = 171
  c = "´"
  if (achar(i) /= "´") stop 1
  if (iachar(c) /= iachar("´")) stop 1
  if (iachar(achar(172)) /= 172) stop 1
  if (iachar ("¨")/= 172) stop 1
  if (achar (172) /= "¨") stop 1
  if ("¨" /= achar ( ichar ( "¨"))) stop 1
  i = 172
  c = "¨"
  if (achar(i) /= "¨") stop 1
  if (iachar(c) /= iachar("¨")) stop 1
  if (iachar(achar(173)) /= 173) stop 1
  if (iachar ("≠")/= 173) stop 1
  if (achar (173) /= "≠") stop 1
  if ("≠" /= achar ( ichar ( "≠"))) stop 1
  i = 173
  c = "≠"
  if (achar(i) /= "≠") stop 1
  if (iachar(c) /= iachar("≠")) stop 1
  if (iachar(achar(174)) /= 174) stop 1
  if (iachar ("Æ")/= 174) stop 1
  if (achar (174) /= "Æ") stop 1
  if ("Æ" /= achar ( ichar ( "Æ"))) stop 1
  i = 174
  c = "Æ"
  if (achar(i) /= "Æ") stop 1
  if (iachar(c) /= iachar("Æ")) stop 1
  if (iachar(achar(175)) /= 175) stop 1
  if (iachar ("Ø")/= 175) stop 1
  if (achar (175) /= "Ø") stop 1
  if ("Ø" /= achar ( ichar ( "Ø"))) stop 1
  i = 175
  c = "Ø"
  if (achar(i) /= "Ø") stop 1
  if (iachar(c) /= iachar("Ø")) stop 1
  if (iachar(achar(176)) /= 176) stop 1
  if (iachar ("∞")/= 176) stop 1
  if (achar (176) /= "∞") stop 1
  if ("∞" /= achar ( ichar ( "∞"))) stop 1
  i = 176
  c = "∞"
  if (achar(i) /= "∞") stop 1
  if (iachar(c) /= iachar("∞")) stop 1
  if (iachar(achar(177)) /= 177) stop 1
  if (iachar ("±")/= 177) stop 1
  if (achar (177) /= "±") stop 1
  if ("±" /= achar ( ichar ( "±"))) stop 1
  i = 177
  c = "±"
  if (achar(i) /= "±") stop 1
  if (iachar(c) /= iachar("±")) stop 1
  if (iachar(achar(178)) /= 178) stop 1
  if (iachar ("≤")/= 178) stop 1
  if (achar (178) /= "≤") stop 1
  if ("≤" /= achar ( ichar ( "≤"))) stop 1
  i = 178
  c = "≤"
  if (achar(i) /= "≤") stop 1
  if (iachar(c) /= iachar("≤")) stop 1
  if (iachar(achar(179)) /= 179) stop 1
  if (iachar ("≥")/= 179) stop 1
  if (achar (179) /= "≥") stop 1
  if ("≥" /= achar ( ichar ( "≥"))) stop 1
  i = 179
  c = "≥"
  if (achar(i) /= "≥") stop 1
  if (iachar(c) /= iachar("≥")) stop 1
  if (iachar(achar(180)) /= 180) stop 1
  if (iachar ("¥")/= 180) stop 1
  if (achar (180) /= "¥") stop 1
  if ("¥" /= achar ( ichar ( "¥"))) stop 1
  i = 180
  c = "¥"
  if (achar(i) /= "¥") stop 1
  if (iachar(c) /= iachar("¥")) stop 1
  if (iachar(achar(181)) /= 181) stop 1
  if (iachar ("µ")/= 181) stop 1
  if (achar (181) /= "µ") stop 1
  if ("µ" /= achar ( ichar ( "µ"))) stop 1
  i = 181
  c = "µ"
  if (achar(i) /= "µ") stop 1
  if (iachar(c) /= iachar("µ")) stop 1
  if (iachar(achar(182)) /= 182) stop 1
  if (iachar ("∂")/= 182) stop 1
  if (achar (182) /= "∂") stop 1
  if ("∂" /= achar ( ichar ( "∂"))) stop 1
  i = 182
  c = "∂"
  if (achar(i) /= "∂") stop 1
  if (iachar(c) /= iachar("∂")) stop 1
  if (iachar(achar(183)) /= 183) stop 1
  if (iachar ("∑")/= 183) stop 1
  if (achar (183) /= "∑") stop 1
  if ("∑" /= achar ( ichar ( "∑"))) stop 1
  i = 183
  c = "∑"
  if (achar(i) /= "∑") stop 1
  if (iachar(c) /= iachar("∑")) stop 1
  if (iachar(achar(184)) /= 184) stop 1
  if (iachar ("∏")/= 184) stop 1
  if (achar (184) /= "∏") stop 1
  if ("∏" /= achar ( ichar ( "∏"))) stop 1
  i = 184
  c = "∏"
  if (achar(i) /= "∏") stop 1
  if (iachar(c) /= iachar("∏")) stop 1
  if (iachar(achar(185)) /= 185) stop 1
  if (iachar ("π")/= 185) stop 1
  if (achar (185) /= "π") stop 1
  if ("π" /= achar ( ichar ( "π"))) stop 1
  i = 185
  c = "π"
  if (achar(i) /= "π") stop 1
  if (iachar(c) /= iachar("π")) stop 1
  if (iachar(achar(186)) /= 186) stop 1
  if (iachar ("∫")/= 186) stop 1
  if (achar (186) /= "∫") stop 1
  if ("∫" /= achar ( ichar ( "∫"))) stop 1
  i = 186
  c = "∫"
  if (achar(i) /= "∫") stop 1
  if (iachar(c) /= iachar("∫")) stop 1
  if (iachar(achar(187)) /= 187) stop 1
  if (iachar ("ª")/= 187) stop 1
  if (achar (187) /= "ª") stop 1
  if ("ª" /= achar ( ichar ( "ª"))) stop 1
  i = 187
  c = "ª"
  if (achar(i) /= "ª") stop 1
  if (iachar(c) /= iachar("ª")) stop 1
  if (iachar(achar(188)) /= 188) stop 1
  if (iachar ("º")/= 188) stop 1
  if (achar (188) /= "º") stop 1
  if ("º" /= achar ( ichar ( "º"))) stop 1
  i = 188
  c = "º"
  if (achar(i) /= "º") stop 1
  if (iachar(c) /= iachar("º")) stop 1
  if (iachar(achar(189)) /= 189) stop 1
  if (iachar ("Ω")/= 189) stop 1
  if (achar (189) /= "Ω") stop 1
  if ("Ω" /= achar ( ichar ( "Ω"))) stop 1
  i = 189
  c = "Ω"
  if (achar(i) /= "Ω") stop 1
  if (iachar(c) /= iachar("Ω")) stop 1
  if (iachar(achar(190)) /= 190) stop 1
  if (iachar ("æ")/= 190) stop 1
  if (achar (190) /= "æ") stop 1
  if ("æ" /= achar ( ichar ( "æ"))) stop 1
  i = 190
  c = "æ"
  if (achar(i) /= "æ") stop 1
  if (iachar(c) /= iachar("æ")) stop 1
  if (iachar(achar(191)) /= 191) stop 1
  if (iachar ("ø")/= 191) stop 1
  if (achar (191) /= "ø") stop 1
  if ("ø" /= achar ( ichar ( "ø"))) stop 1
  i = 191
  c = "ø"
  if (achar(i) /= "ø") stop 1
  if (iachar(c) /= iachar("ø")) stop 1
  if (iachar(achar(192)) /= 192) stop 1
  if (iachar ("¿")/= 192) stop 1
  if (achar (192) /= "¿") stop 1
  if ("¿" /= achar ( ichar ( "¿"))) stop 1
  i = 192
  c = "¿"
  if (achar(i) /= "¿") stop 1
  if (iachar(c) /= iachar("¿")) stop 1
  if (iachar(achar(193)) /= 193) stop 1
  if (iachar ("¡")/= 193) stop 1
  if (achar (193) /= "¡") stop 1
  if ("¡" /= achar ( ichar ( "¡"))) stop 1
  i = 193
  c = "¡"
  if (achar(i) /= "¡") stop 1
  if (iachar(c) /= iachar("¡")) stop 1
  if (iachar(achar(194)) /= 194) stop 1
  if (iachar ("¬")/= 194) stop 1
  if (achar (194) /= "¬") stop 1
  if ("¬" /= achar ( ichar ( "¬"))) stop 1
  i = 194
  c = "¬"
  if (achar(i) /= "¬") stop 1
  if (iachar(c) /= iachar("¬")) stop 1
  if (iachar(achar(195)) /= 195) stop 1
  if (iachar ("√")/= 195) stop 1
  if (achar (195) /= "√") stop 1
  if ("√" /= achar ( ichar ( "√"))) stop 1
  i = 195
  c = "√"
  if (achar(i) /= "√") stop 1
  if (iachar(c) /= iachar("√")) stop 1
  if (iachar(achar(196)) /= 196) stop 1
  if (iachar ("ƒ")/= 196) stop 1
  if (achar (196) /= "ƒ") stop 1
  if ("ƒ" /= achar ( ichar ( "ƒ"))) stop 1
  i = 196
  c = "ƒ"
  if (achar(i) /= "ƒ") stop 1
  if (iachar(c) /= iachar("ƒ")) stop 1
  if (iachar(achar(197)) /= 197) stop 1
  if (iachar ("≈")/= 197) stop 1
  if (achar (197) /= "≈") stop 1
  if ("≈" /= achar ( ichar ( "≈"))) stop 1
  i = 197
  c = "≈"
  if (achar(i) /= "≈") stop 1
  if (iachar(c) /= iachar("≈")) stop 1
  if (iachar(achar(198)) /= 198) stop 1
  if (iachar ("∆")/= 198) stop 1
  if (achar (198) /= "∆") stop 1
  if ("∆" /= achar ( ichar ( "∆"))) stop 1
  i = 198
  c = "∆"
  if (achar(i) /= "∆") stop 1
  if (iachar(c) /= iachar("∆")) stop 1
  if (iachar(achar(199)) /= 199) stop 1
  if (iachar ("«")/= 199) stop 1
  if (achar (199) /= "«") stop 1
  if ("«" /= achar ( ichar ( "«"))) stop 1
  i = 199
  c = "«"
  if (achar(i) /= "«") stop 1
  if (iachar(c) /= iachar("«")) stop 1
  if (iachar(achar(200)) /= 200) stop 1
  if (iachar ("»")/= 200) stop 1
  if (achar (200) /= "»") stop 1
  if ("»" /= achar ( ichar ( "»"))) stop 1
  i = 200
  c = "»"
  if (achar(i) /= "»") stop 1
  if (iachar(c) /= iachar("»")) stop 1
  if (iachar(achar(201)) /= 201) stop 1
  if (iachar ("…")/= 201) stop 1
  if (achar (201) /= "…") stop 1
  if ("…" /= achar ( ichar ( "…"))) stop 1
  i = 201
  c = "…"
  if (achar(i) /= "…") stop 1
  if (iachar(c) /= iachar("…")) stop 1
  if (iachar(achar(202)) /= 202) stop 1
  if (iachar (" ")/= 202) stop 1
  if (achar (202) /= " ") stop 1
  if (" " /= achar ( ichar ( " "))) stop 1
  i = 202
  c = " "
  if (achar(i) /= " ") stop 1
  if (iachar(c) /= iachar(" ")) stop 1
  if (iachar(achar(203)) /= 203) stop 1
  if (iachar ("À")/= 203) stop 1
  if (achar (203) /= "À") stop 1
  if ("À" /= achar ( ichar ( "À"))) stop 1
  i = 203
  c = "À"
  if (achar(i) /= "À") stop 1
  if (iachar(c) /= iachar("À")) stop 1
  if (iachar(achar(204)) /= 204) stop 1
  if (iachar ("Ã")/= 204) stop 1
  if (achar (204) /= "Ã") stop 1
  if ("Ã" /= achar ( ichar ( "Ã"))) stop 1
  i = 204
  c = "Ã"
  if (achar(i) /= "Ã") stop 1
  if (iachar(c) /= iachar("Ã")) stop 1
  if (iachar(achar(205)) /= 205) stop 1
  if (iachar ("Õ")/= 205) stop 1
  if (achar (205) /= "Õ") stop 1
  if ("Õ" /= achar ( ichar ( "Õ"))) stop 1
  i = 205
  c = "Õ"
  if (achar(i) /= "Õ") stop 1
  if (iachar(c) /= iachar("Õ")) stop 1
  if (iachar(achar(206)) /= 206) stop 1
  if (iachar ("Œ")/= 206) stop 1
  if (achar (206) /= "Œ") stop 1
  if ("Œ" /= achar ( ichar ( "Œ"))) stop 1
  i = 206
  c = "Œ"
  if (achar(i) /= "Œ") stop 1
  if (iachar(c) /= iachar("Œ")) stop 1
  if (iachar(achar(207)) /= 207) stop 1
  if (iachar ("œ")/= 207) stop 1
  if (achar (207) /= "œ") stop 1
  if ("œ" /= achar ( ichar ( "œ"))) stop 1
  i = 207
  c = "œ"
  if (achar(i) /= "œ") stop 1
  if (iachar(c) /= iachar("œ")) stop 1
  if (iachar(achar(208)) /= 208) stop 1
  if (iachar ("–")/= 208) stop 1
  if (achar (208) /= "–") stop 1
  if ("–" /= achar ( ichar ( "–"))) stop 1
  i = 208
  c = "–"
  if (achar(i) /= "–") stop 1
  if (iachar(c) /= iachar("–")) stop 1
  if (iachar(achar(209)) /= 209) stop 1
  if (iachar ("—")/= 209) stop 1
  if (achar (209) /= "—") stop 1
  if ("—" /= achar ( ichar ( "—"))) stop 1
  i = 209
  c = "—"
  if (achar(i) /= "—") stop 1
  if (iachar(c) /= iachar("—")) stop 1
  if (iachar(achar(210)) /= 210) stop 1
  if (iachar ("“")/= 210) stop 1
  if (achar (210) /= "“") stop 1
  if ("“" /= achar ( ichar ( "“"))) stop 1
  i = 210
  c = "“"
  if (achar(i) /= "“") stop 1
  if (iachar(c) /= iachar("“")) stop 1
  if (iachar(achar(211)) /= 211) stop 1
  if (iachar ("”")/= 211) stop 1
  if (achar (211) /= "”") stop 1
  if ("”" /= achar ( ichar ( "”"))) stop 1
  i = 211
  c = "”"
  if (achar(i) /= "”") stop 1
  if (iachar(c) /= iachar("”")) stop 1
  if (iachar(achar(212)) /= 212) stop 1
  if (iachar ("‘")/= 212) stop 1
  if (achar (212) /= "‘") stop 1
  if ("‘" /= achar ( ichar ( "‘"))) stop 1
  i = 212
  c = "‘"
  if (achar(i) /= "‘") stop 1
  if (iachar(c) /= iachar("‘")) stop 1
  if (iachar(achar(213)) /= 213) stop 1
  if (iachar ("’")/= 213) stop 1
  if (achar (213) /= "’") stop 1
  if ("’" /= achar ( ichar ( "’"))) stop 1
  i = 213
  c = "’"
  if (achar(i) /= "’") stop 1
  if (iachar(c) /= iachar("’")) stop 1
  if (iachar(achar(214)) /= 214) stop 1
  if (iachar ("÷")/= 214) stop 1
  if (achar (214) /= "÷") stop 1
  if ("÷" /= achar ( ichar ( "÷"))) stop 1
  i = 214
  c = "÷"
  if (achar(i) /= "÷") stop 1
  if (iachar(c) /= iachar("÷")) stop 1
  if (iachar(achar(215)) /= 215) stop 1
  if (iachar ("◊")/= 215) stop 1
  if (achar (215) /= "◊") stop 1
  if ("◊" /= achar ( ichar ( "◊"))) stop 1
  i = 215
  c = "◊"
  if (achar(i) /= "◊") stop 1
  if (iachar(c) /= iachar("◊")) stop 1
  if (iachar(achar(216)) /= 216) stop 1
  if (iachar ("ÿ")/= 216) stop 1
  if (achar (216) /= "ÿ") stop 1
  if ("ÿ" /= achar ( ichar ( "ÿ"))) stop 1
  i = 216
  c = "ÿ"
  if (achar(i) /= "ÿ") stop 1
  if (iachar(c) /= iachar("ÿ")) stop 1
  if (iachar(achar(217)) /= 217) stop 1
  if (iachar ("Ÿ")/= 217) stop 1
  if (achar (217) /= "Ÿ") stop 1
  if ("Ÿ" /= achar ( ichar ( "Ÿ"))) stop 1
  i = 217
  c = "Ÿ"
  if (achar(i) /= "Ÿ") stop 1
  if (iachar(c) /= iachar("Ÿ")) stop 1
  if (iachar(achar(218)) /= 218) stop 1
  if (iachar ("⁄")/= 218) stop 1
  if (achar (218) /= "⁄") stop 1
  if ("⁄" /= achar ( ichar ( "⁄"))) stop 1
  i = 218
  c = "⁄"
  if (achar(i) /= "⁄") stop 1
  if (iachar(c) /= iachar("⁄")) stop 1
  if (iachar(achar(219)) /= 219) stop 1
  if (iachar ("€")/= 219) stop 1
  if (achar (219) /= "€") stop 1
  if ("€" /= achar ( ichar ( "€"))) stop 1
  i = 219
  c = "€"
  if (achar(i) /= "€") stop 1
  if (iachar(c) /= iachar("€")) stop 1
  if (iachar(achar(220)) /= 220) stop 1
  if (iachar ("‹")/= 220) stop 1
  if (achar (220) /= "‹") stop 1
  if ("‹" /= achar ( ichar ( "‹"))) stop 1
  i = 220
  c = "‹"
  if (achar(i) /= "‹") stop 1
  if (iachar(c) /= iachar("‹")) stop 1
  if (iachar(achar(221)) /= 221) stop 1
  if (iachar ("›")/= 221) stop 1
  if (achar (221) /= "›") stop 1
  if ("›" /= achar ( ichar ( "›"))) stop 1
  i = 221
  c = "›"
  if (achar(i) /= "›") stop 1
  if (iachar(c) /= iachar("›")) stop 1
  if (iachar(achar(222)) /= 222) stop 1
  if (iachar ("ﬁ")/= 222) stop 1
  if (achar (222) /= "ﬁ") stop 1
  if ("ﬁ" /= achar ( ichar ( "ﬁ"))) stop 1
  i = 222
  c = "ﬁ"
  if (achar(i) /= "ﬁ") stop 1
  if (iachar(c) /= iachar("ﬁ")) stop 1
  if (iachar(achar(223)) /= 223) stop 1
  if (iachar ("ﬂ")/= 223) stop 1
  if (achar (223) /= "ﬂ") stop 1
  if ("ﬂ" /= achar ( ichar ( "ﬂ"))) stop 1
  i = 223
  c = "ﬂ"
  if (achar(i) /= "ﬂ") stop 1
  if (iachar(c) /= iachar("ﬂ")) stop 1
  if (iachar(achar(224)) /= 224) stop 1
  if (iachar ("‡")/= 224) stop 1
  if (achar (224) /= "‡") stop 1
  if ("‡" /= achar ( ichar ( "‡"))) stop 1
  i = 224
  c = "‡"
  if (achar(i) /= "‡") stop 1
  if (iachar(c) /= iachar("‡")) stop 1
  if (iachar(achar(225)) /= 225) stop 1
  if (iachar ("·")/= 225) stop 1
  if (achar (225) /= "·") stop 1
  if ("·" /= achar ( ichar ( "·"))) stop 1
  i = 225
  c = "·"
  if (achar(i) /= "·") stop 1
  if (iachar(c) /= iachar("·")) stop 1
  if (iachar(achar(226)) /= 226) stop 1
  if (iachar ("‚")/= 226) stop 1
  if (achar (226) /= "‚") stop 1
  if ("‚" /= achar ( ichar ( "‚"))) stop 1
  i = 226
  c = "‚"
  if (achar(i) /= "‚") stop 1
  if (iachar(c) /= iachar("‚")) stop 1
  if (iachar(achar(227)) /= 227) stop 1
  if (iachar ("„")/= 227) stop 1
  if (achar (227) /= "„") stop 1
  if ("„" /= achar ( ichar ( "„"))) stop 1
  i = 227
  c = "„"
  if (achar(i) /= "„") stop 1
  if (iachar(c) /= iachar("„")) stop 1
  if (iachar(achar(228)) /= 228) stop 1
  if (iachar ("‰")/= 228) stop 1
  if (achar (228) /= "‰") stop 1
  if ("‰" /= achar ( ichar ( "‰"))) stop 1
  i = 228
  c = "‰"
  if (achar(i) /= "‰") stop 1
  if (iachar(c) /= iachar("‰")) stop 1
  if (iachar(achar(229)) /= 229) stop 1
  if (iachar ("Â")/= 229) stop 1
  if (achar (229) /= "Â") stop 1
  if ("Â" /= achar ( ichar ( "Â"))) stop 1
  i = 229
  c = "Â"
  if (achar(i) /= "Â") stop 1
  if (iachar(c) /= iachar("Â")) stop 1
  if (iachar(achar(230)) /= 230) stop 1
  if (iachar ("Ê")/= 230) stop 1
  if (achar (230) /= "Ê") stop 1
  if ("Ê" /= achar ( ichar ( "Ê"))) stop 1
  i = 230
  c = "Ê"
  if (achar(i) /= "Ê") stop 1
  if (iachar(c) /= iachar("Ê")) stop 1
  if (iachar(achar(231)) /= 231) stop 1
  if (iachar ("Á")/= 231) stop 1
  if (achar (231) /= "Á") stop 1
  if ("Á" /= achar ( ichar ( "Á"))) stop 1
  i = 231
  c = "Á"
  if (achar(i) /= "Á") stop 1
  if (iachar(c) /= iachar("Á")) stop 1
  if (iachar(achar(232)) /= 232) stop 1
  if (iachar ("Ë")/= 232) stop 1
  if (achar (232) /= "Ë") stop 1
  if ("Ë" /= achar ( ichar ( "Ë"))) stop 1
  i = 232
  c = "Ë"
  if (achar(i) /= "Ë") stop 1
  if (iachar(c) /= iachar("Ë")) stop 1
  if (iachar(achar(233)) /= 233) stop 1
  if (iachar ("È")/= 233) stop 1
  if (achar (233) /= "È") stop 1
  if ("È" /= achar ( ichar ( "È"))) stop 1
  i = 233
  c = "È"
  if (achar(i) /= "È") stop 1
  if (iachar(c) /= iachar("È")) stop 1
  if (iachar(achar(234)) /= 234) stop 1
  if (iachar ("Í")/= 234) stop 1
  if (achar (234) /= "Í") stop 1
  if ("Í" /= achar ( ichar ( "Í"))) stop 1
  i = 234
  c = "Í"
  if (achar(i) /= "Í") stop 1
  if (iachar(c) /= iachar("Í")) stop 1
  if (iachar(achar(235)) /= 235) stop 1
  if (iachar ("Î")/= 235) stop 1
  if (achar (235) /= "Î") stop 1
  if ("Î" /= achar ( ichar ( "Î"))) stop 1
  i = 235
  c = "Î"
  if (achar(i) /= "Î") stop 1
  if (iachar(c) /= iachar("Î")) stop 1
  if (iachar(achar(236)) /= 236) stop 1
  if (iachar ("Ï")/= 236) stop 1
  if (achar (236) /= "Ï") stop 1
  if ("Ï" /= achar ( ichar ( "Ï"))) stop 1
  i = 236
  c = "Ï"
  if (achar(i) /= "Ï") stop 1
  if (iachar(c) /= iachar("Ï")) stop 1
  if (iachar(achar(237)) /= 237) stop 1
  if (iachar ("Ì")/= 237) stop 1
  if (achar (237) /= "Ì") stop 1
  if ("Ì" /= achar ( ichar ( "Ì"))) stop 1
  i = 237
  c = "Ì"
  if (achar(i) /= "Ì") stop 1
  if (iachar(c) /= iachar("Ì")) stop 1
  if (iachar(achar(238)) /= 238) stop 1
  if (iachar ("Ó")/= 238) stop 1
  if (achar (238) /= "Ó") stop 1
  if ("Ó" /= achar ( ichar ( "Ó"))) stop 1
  i = 238
  c = "Ó"
  if (achar(i) /= "Ó") stop 1
  if (iachar(c) /= iachar("Ó")) stop 1
  if (iachar(achar(239)) /= 239) stop 1
  if (iachar ("Ô")/= 239) stop 1
  if (achar (239) /= "Ô") stop 1
  if ("Ô" /= achar ( ichar ( "Ô"))) stop 1
  i = 239
  c = "Ô"
  if (achar(i) /= "Ô") stop 1
  if (iachar(c) /= iachar("Ô")) stop 1
  if (iachar(achar(240)) /= 240) stop 1
  if (iachar ("")/= 240) stop 1
  if (achar (240) /= "") stop 1
  if ("" /= achar ( ichar ( ""))) stop 1
  i = 240
  c = ""
  if (achar(i) /= "") stop 1
  if (iachar(c) /= iachar("")) stop 1
  if (iachar(achar(241)) /= 241) stop 1
  if (iachar ("Ò")/= 241) stop 1
  if (achar (241) /= "Ò") stop 1
  if ("Ò" /= achar ( ichar ( "Ò"))) stop 1
  i = 241
  c = "Ò"
  if (achar(i) /= "Ò") stop 1
  if (iachar(c) /= iachar("Ò")) stop 1
  if (iachar(achar(242)) /= 242) stop 1
  if (iachar ("Ú")/= 242) stop 1
  if (achar (242) /= "Ú") stop 1
  if ("Ú" /= achar ( ichar ( "Ú"))) stop 1
  i = 242
  c = "Ú"
  if (achar(i) /= "Ú") stop 1
  if (iachar(c) /= iachar("Ú")) stop 1
  if (iachar(achar(243)) /= 243) stop 1
  if (iachar ("Û")/= 243) stop 1
  if (achar (243) /= "Û") stop 1
  if ("Û" /= achar ( ichar ( "Û"))) stop 1
  i = 243
  c = "Û"
  if (achar(i) /= "Û") stop 1
  if (iachar(c) /= iachar("Û")) stop 1
  if (iachar(achar(244)) /= 244) stop 1
  if (iachar ("Ù")/= 244) stop 1
  if (achar (244) /= "Ù") stop 1
  if ("Ù" /= achar ( ichar ( "Ù"))) stop 1
  i = 244
  c = "Ù"
  if (achar(i) /= "Ù") stop 1
  if (iachar(c) /= iachar("Ù")) stop 1
  if (iachar(achar(245)) /= 245) stop 1
  if (iachar ("ı")/= 245) stop 1
  if (achar (245) /= "ı") stop 1
  if ("ı" /= achar ( ichar ( "ı"))) stop 1
  i = 245
  c = "ı"
  if (achar(i) /= "ı") stop 1
  if (iachar(c) /= iachar("ı")) stop 1
  if (iachar(achar(246)) /= 246) stop 1
  if (iachar ("ˆ")/= 246) stop 1
  if (achar (246) /= "ˆ") stop 1
  if ("ˆ" /= achar ( ichar ( "ˆ"))) stop 1
  i = 246
  c = "ˆ"
  if (achar(i) /= "ˆ") stop 1
  if (iachar(c) /= iachar("ˆ")) stop 1
  if (iachar(achar(247)) /= 247) stop 1
  if (iachar ("˜")/= 247) stop 1
  if (achar (247) /= "˜") stop 1
  if ("˜" /= achar ( ichar ( "˜"))) stop 1
  i = 247
  c = "˜"
  if (achar(i) /= "˜") stop 1
  if (iachar(c) /= iachar("˜")) stop 1
  if (iachar(achar(248)) /= 248) stop 1
  if (iachar ("¯")/= 248) stop 1
  if (achar (248) /= "¯") stop 1
  if ("¯" /= achar ( ichar ( "¯"))) stop 1
  i = 248
  c = "¯"
  if (achar(i) /= "¯") stop 1
  if (iachar(c) /= iachar("¯")) stop 1
  if (iachar(achar(249)) /= 249) stop 1
  if (iachar ("˘")/= 249) stop 1
  if (achar (249) /= "˘") stop 1
  if ("˘" /= achar ( ichar ( "˘"))) stop 1
  i = 249
  c = "˘"
  if (achar(i) /= "˘") stop 1
  if (iachar(c) /= iachar("˘")) stop 1
  if (iachar(achar(250)) /= 250) stop 1
  if (iachar ("˙")/= 250) stop 1
  if (achar (250) /= "˙") stop 1
  if ("˙" /= achar ( ichar ( "˙"))) stop 1
  i = 250
  c = "˙"
  if (achar(i) /= "˙") stop 1
  if (iachar(c) /= iachar("˙")) stop 1
  if (iachar(achar(251)) /= 251) stop 1
  if (iachar ("˚")/= 251) stop 1
  if (achar (251) /= "˚") stop 1
  if ("˚" /= achar ( ichar ( "˚"))) stop 1
  i = 251
  c = "˚"
  if (achar(i) /= "˚") stop 1
  if (iachar(c) /= iachar("˚")) stop 1
  if (iachar(achar(252)) /= 252) stop 1
  if (iachar ("¸")/= 252) stop 1
  if (achar (252) /= "¸") stop 1
  if ("¸" /= achar ( ichar ( "¸"))) stop 1
  i = 252
  c = "¸"
  if (achar(i) /= "¸") stop 1
  if (iachar(c) /= iachar("¸")) stop 1
  if (iachar(achar(253)) /= 253) stop 1
  if (iachar ("˝")/= 253) stop 1
  if (achar (253) /= "˝") stop 1
  if ("˝" /= achar ( ichar ( "˝"))) stop 1
  i = 253
  c = "˝"
  if (achar(i) /= "˝") stop 1
  if (iachar(c) /= iachar("˝")) stop 1
  if (iachar(achar(254)) /= 254) stop 1
  if (iachar ("˛")/= 254) stop 1
  if (achar (254) /= "˛") stop 1
  if ("˛" /= achar ( ichar ( "˛"))) stop 1
  i = 254
  c = "˛"
  if (achar(i) /= "˛") stop 1
  if (iachar(c) /= iachar("˛")) stop 1
  if (iachar(achar(255)) /= 255) stop 1
  if (iachar ("ˇ")/= 255) stop 1
  if (achar (255) /= "ˇ") stop 1
  if ("ˇ" /= achar ( ichar ( "ˇ"))) stop 1
  i = 255
  c = "ˇ"
  if (achar(i) /= "ˇ") stop 1
  if (iachar(c) /= iachar("ˇ")) stop 1
end program main
